FROM python:3

COPY requirements.txt /app/requirements.txt

WORKDIR /app

RUN apt-get -q update && apt-get -qy install netcat

RUN pip install -r requirements.txt

RUN useradd --create-home --shell /bin/bash app_user

COPY . .

USER app_user

CMD [ "bash", "run_dev.sh" ]